<a href="https://colab.research.google.com/github/satyam26en/satyam26en/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.1  Installing NumPy

# **1.3  Numpy**

***Understanding the Differences Between NumPy Arrays and Python Lists***

## Introduction

Python lists are versatile and widely used for various purposes, but when it comes to numerical operations and large-scale data manipulation, NumPy arrays offer significant advantages in terms of performance and functionality.

### Key Differences Between NumPy Arrays and Python Lists

| **Feature**                     | **Python Lists**                                            | **NumPy Arrays**                                          |
|---------------------------------|-------------------------------------------------------------|-----------------------------------------------------------|
| **Homogeneity**                 | Can contain elements of different data types.               | Must contain elements of the same data type.              |
| **Memory Efficiency**           | Less memory efficient; stores each element as a full Python object. | More memory efficient; stores elements in a continuous block of memory. |
| **Performance**                 | Slower for numerical operations due to overhead of dynamic typing. | Faster for numerical operations due to fixed data types and low-level optimizations. |
| **Mathematical Operations**     | Limited built-in support for element-wise operations.       | Extensive support for element-wise operations and broadcasting. |
| **Functionality**               | General-purpose, suitable for diverse tasks.                | Designed specifically for numerical computations and array operations. |
| **Dimensionality**              | Primarily supports 1D (list) or nested lists for higher dimensions. | Natively supports multi-dimensional arrays (1D, 2D, 3D, etc.). |
| **Slicing and Indexing**        | Supports simple slicing and indexing.                       | Advanced slicing, indexing, and broadcasting capabilities. |






In [5]:
import numpy as np

# **1.4  Creating array in numpy**

### 1. Converting Python Lists to NumPy Arrays

In [36]:
# Creating a 1D NumPy array from a Python list
list_1d = [1, 2, 3, 4, 5]
array_1d = np.array(list_1d)
print("1D Array:", array_1d)

1D Array: [1 2 3 4 5]


In [37]:
array_1d.ndim # type of array like 1-d,2-d array

1

In [38]:
# Creating a 2D NumPy array from a nested Python list
list_2d = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(list_2d)
print("2D Array:\n", array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [39]:
array_2d.ndim # type of array like 1-d,2-d array

2

**Key Points:**

The np.array() function converts a Python list (or nested list) into a NumPy array.
The resulting NumPy array inherits the data type from the list elements or automatically converts mixed types to the most appropriate type (e.g., converting integers to floats if necessary).

### 2. Creating Arrays with Default Values

***1.*** np.zeros(): Creates an array filled with zeros.

In [40]:
# Creating a 1D array of zeros
zeros_1d = np.zeros(5)
print("1D Array of zeros:", zeros_1d)

1D Array of zeros: [0. 0. 0. 0. 0.]


In [41]:
# Creating a 2D array of zeros
zeros_2d = np.zeros((2, 3))
print("2D Array of zeros:\n", zeros_2d)

2D Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


***2.*** np.ones(): Creates an array filled with ones.

In [42]:
# Creating a 1D array of ones
ones_1d = np.ones(4)
print("1D Array of ones:", ones_1d)

1D Array of ones: [1. 1. 1. 1.]


In [43]:
# Creating a 2D array of ones
ones_2d = np.ones((3, 2))
print("2D Array of ones:\n", ones_2d)

2D Array of ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


***3.*** np.full(): Creates an array filled with a specified constant value.

In [44]:
# Creating a 1D array filled with the value 7
full_1d = np.full(5, 7)
print("1D Array filled with 7s:", full_1d)

1D Array filled with 7s: [7 7 7 7 7]


In [45]:
# Creating a 2D array filled with the value 9
full_2d = np.full((2, 3), 9)
print("2D Array filled with 9s:\n", full_2d)

2D Array filled with 9s:
 [[9 9 9]
 [9 9 9]]


### 3. Creating Arrays with a Range of Values

***1.*** np.arange(): Creates an array with a sequence of values, similar to Python's range() function.

In [46]:
# Creating an array with values from 0 to 9
arange_array = np.arange(10)
print("Array with arange:", arange_array)

Array with arange: [0 1 2 3 4 5 6 7 8 9]


In [47]:
# Creating an array with values from 0 to 9 with a step of 2
arange_step_array = np.arange(0, 10, 2)
print("Array with arange and step of 2:", arange_step_array)

Array with arange and step of 2: [0 2 4 6 8]


***2.*** np.linspace(): Creates an array with evenly spaced values over a specified interval.

In [48]:
# Creating an array with 5 evenly spaced values between 0 and 1
linspace_array = np.linspace(0, 1, 5)
print("Array with linspace:", linspace_array)

Array with linspace: [0.   0.25 0.5  0.75 1.  ]


### 4. Creating Identity and Diagonal Matrices

***1.*** np.eye(): Creates an identity matrix

In [49]:
# Creating a 3x3 identity matrix
identity_matrix = np.eye(3)
print("Identity matrix:\n", identity_matrix)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


***2.*** np.diag(): Creates a diagonal matrix or extracts the diagonal of a matrix

In [50]:
# Creating a diagonal matrix with specified values on the diagonal
diagonal_matrix = np.diag([1, 2, 3])
print("Diagonal matrix:\n", diagonal_matrix)

Diagonal matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [51]:
# Extracting the diagonal from an existing matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diagonal_values = np.diag(matrix)
print("Extracted diagonal:", diagonal_values)

Extracted diagonal: [1 5 9]


### 5. Creating Arrays from Random Values

***1.*** np.random.rand(): Creates an array with random values from a uniform distribution over [0, 1]

In [52]:
# Creating a 1D array with 5 random values
random_array = np.random.rand(5)
print("Random array:", random_array)

Random array: [0.7350389  0.27744834 0.21355534 0.09324471 0.32858692]


In [53]:
# Creating a 2D array with random values
random_array_2d = np.random.rand(2, 3)
print("Random 2D array:\n", random_array_2d)

Random 2D array:
 [[0.63350845 0.88415736 0.71557566]
 [0.21957283 0.92964756 0.66555769]]


***2.*** np.random.randn(): Creates an array with random values from a standard normal distribution (mean = 0, variance = 1).

In [54]:
# Creating a 1D array with random values from the standard normal distribution
randn_array = np.random.randn(5)
print("Standard normal distribution array:", randn_array)

Standard normal distribution array: [ 0.31049379  0.00961945  0.68462822 -0.23455531  0.55483326]


In [55]:
# Creating a 2D array with random values
randn_array_2d = np.random.randn(2, 3)
print("Standard normal distribution 2D array:\n", randn_array_2d)

Standard normal distribution 2D array:
 [[ 1.60923596  1.97946783  0.08361017]
 [-0.42343709 -0.04335305  1.10568351]]


***3.*** np.random.randint(): Creates an array with random integers from a specified range

In [56]:
# Creating a 1D array with 5 random integers between 0 and 10
randint_array = np.random.randint(0, 10, 5)
print("Random integers array:", randint_array)

Random integers array: [1 1 1 2 9]


In [57]:
# Creating a 2D array with random integers
randint_array_2d = np.random.randint(0, 10, (2, 3))
print("Random integers 2D array:\n", randint_array_2d)

Random integers 2D array:
 [[3 6 3]
 [5 3 9]]


# DAY_1 RECAP:

## Day 1 Recap: Understanding and Creating NumPy Arrays

1. **Differences Between NumPy Arrays and Python Lists**:
   - **Homogeneity**: NumPy arrays are homogeneous, while Python lists can contain mixed data types.
   - **Memory Efficiency**: NumPy arrays use less memory and are more efficient for numerical data.
   - **Performance**: NumPy arrays are optimized for numerical operations and are faster than Python lists.
   - **Mathematical Operations**: NumPy arrays support a wide range of element-wise and matrix operations.
   - **Functionality**: NumPy is designed for numerical and scientific computing with extensive functionalities.
   - **Dimensionality**: NumPy arrays natively support multi-dimensional data.
   - **Slicing and Indexing**: Advanced slicing and indexing capabilities in NumPy arrays.

2. **Creating Arrays**:
   - **Converting Python Lists to NumPy Arrays**:
     - Use `np.array()` to convert lists (or nested lists) to NumPy arrays.
   - **Creating Arrays with Default Values**:
     - `np.zeros()`: Creates arrays filled with zeros.
     - `np.ones()`: Creates arrays filled with ones.
     - `np.full()`: Creates arrays filled with a specified constant value.
   - **Creating Arrays with a Range of Values**:
     - `np.arange()`: Creates arrays with sequences of values.
     - `np.linspace()`: Creates arrays with evenly spaced values over a specified interval.
   - **Creating Identity and Diagonal Matrices**:
     - `np.eye()`: Creates identity matrices.
     - `np.diag()`: Creates diagonal matrices or extracts diagonals.
   - **Creating Arrays from Random Values**:
     - `np.random.rand()`: Creates arrays with random values from a uniform distribution.
     - `np.random.randn()`: Creates arrays with random values from a standard normal distribution.
     - `np.random.randint()`: Creates arrays with random integers from a specified range.




